name: addFields
type: stage
uri: https://www.mongodb.com/docs/manual/reference/operator/aggregation/addFields/
doc: "Adds new fields to documents. $addFields outputs documents that contain all existing fields from the input documents and newly added fields."
encode: single
args:
  - name: fields
    type: resolvesToObject
    #subtype: expression
