name: count
type: stage
uri: https://www.mongodb.com/docs/manual/reference/operator/aggregation/count/
doc: "Passes a document to the next stage that contains a count of the number of documents input to the stage."
encode: object
args:
  - name: field
    type: resolvesToString
    doc: "The name of the output field which has the count as its value. It must be a non-empty string, must not start with $ and must not contain the . character."
