- name: and
  type: resolvesToBool
  args:
    - name: expressions
      type: expression
      isVariadic: true
      variadicMin: 1
- name: eq
  encode: array
  type: resolvesToBool
  args:
    - name: expression1
      type: expression
    - name: expression2
      type: expression
- name: gt
  encode: array
  type: resolvesToBool
  args:
    - name: expression1
      type: expression
    - name: expression2
      type: expression
- name: lt
  encode: array
  type: resolvesToBool
  args:
    - name: expression1
      type: expression
    - name: expression2
      type: expression
- name: ne
  encode: array
  type: resolvesToBool
  args:
    - name: expression1
      type: expression
    - name: expression2
      type: expression
- name: filter
  encode: object
  type: resolvesToArray
  usesNamedArgs: true
  args:
    - name: input
      type: resolvesToArray
    - name: cond
      type: resolvesToBool
    - name: as
      type: resolvesToString
      isOptional: true
    - name: limit
      type: resolvesToInt
      isOptional: true
- name: sum
  type: resolvesToInt
  args:
    - name: expression
      type: expression