- name: match
  args:
    - name: matchExpr
      type: resolvesToMatchExpression
      isVariadic: true
      variadicMin: 1
- name: sort
  args:
    - name: sortSpecification
      type: resolvesToSortSpecification
- name: limit
  args:
    - name: limit
      type: int
