- name: match
  type: stage
  args:
    - name: query
      type: expression
- name: sort
  type: stage
  args:
    - name: sortSpecification
      type: resolvesToObject
- name: limit
  type: stage
  args:
    - name: limit
      type: resolvesToInt
- name: group
  type: stage
  encode: object
  args:
    # @todo _id is not optional but only nullable
    - name: _id
      type: expression
      isOptional: true
    # @todo fields are optional and encoded at the same level as _id
    - name: fields
      type: resolvesToObject
      isOptional: true
- name: project
  type: stage
  args:
    - name: specifications
      type: resolvesToObject
