- name: match
  args:
    - name: matchExpr
      type: expression
      isVariadic: true
      variadicMin: 1
- name: sort
  args:
    - name: sortSpecification
      type: resolvesToObject
- name: limit
  args:
    - name: limit
      type: resolvesToInt
